### ISSUE TITLE
Tons of https errors

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-classroom-ui#201]
If you enter to a classroom using https - like https://classroom.mumuki.io/#/central/courses -, you will get lots of errors: 

![screenshot_2018-09-26_19-02-28](https://user-images.githubusercontent.com/677436/46111834-c5b94300-c1be-11e8-99a8-ef9a94b5fbd1.png)

```
Mixed Content: The page at 'https://classroom.mumuki.io/#/central/courses' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/lato/v14/S6u8w4BMUTPHjxsAXC-v.ttf'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by rodri042** [comment]
I've run a HTTPS server in localhost with files generated by the `yarn build` command and it works OK, so maybe it's something related to the deploy process. I'll keep looking...

![screenshot2](https://user-images.githubusercontent.com/1631752/49134320-f3576100-f2c1-11e8-8c96-f25a0ea7e9c1.png)

**Comment by flbulgarelli** [comment]
This is not happening anymore in latest version.
