### ISSUE TITLE
Preserve lessons order

### ISSUE THREAD

**Issue by faloi** [mumuki/mumuki-classroom-ui#221]
<a href="https://github.com/faloi"><img src="https://avatars.githubusercontent.com/u/1585835?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [faloi](https://github.com/faloi)**
_Monday Mar 21, 2016 at 00:44 GMT_
_Originally opened as https://github.com/mumuki/mumuki-classroom/issues/14_

---

Right now the order is alphabetical, perhaps when the book is reified on Bibliotheca this could be solved easily.

**Comment by flbulgarelli** [comment]
The order is just fine right now. Only displaying the numbers - `guide.parent.position`-like field - is missing
